/*
FiveWest Client API

Testing DepositAddressAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package fivewestapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pbreedt/fivewestapi"
)

func Test_fivewestapi_DepositAddressAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DepositAddressAPIService GetAllDepositAddressesForSymbolApiV1DepositAddressSymbolGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var symbol string

		resp, httpRes, err := apiClient.DepositAddressAPI.GetAllDepositAddressesForSymbolApiV1DepositAddressSymbolGet(context.Background(), symbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
