/*
FiveWest Client API

Testing WithdrawalRequestAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package fivewestapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pbreedt/fivewestapi"
)

func Test_fivewestapi_WithdrawalRequestAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WithdrawalRequestAPIService CancelWithdrawalRequestApiV1WithdrawalRequestIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		httpRes, err := apiClient.WithdrawalRequestAPI.CancelWithdrawalRequestApiV1WithdrawalRequestIdPatch(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WithdrawalRequestAPIService CreateWithdrawalRequestApiV1WithdrawalRequestPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WithdrawalRequestAPI.CreateWithdrawalRequestApiV1WithdrawalRequestPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WithdrawalRequestAPIService GetAllWithdrawalRequestsApiV1WithdrawalRequestGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WithdrawalRequestAPI.GetAllWithdrawalRequestsApiV1WithdrawalRequestGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
