/*
FiveWest Client API

API Documentation for FiveWest's wallet and RfQ trading services. Please visit dashboard.fivewest.co.za to sign up. Once your account has been verified to the sufficient level necessary for the given service, you can create an API key and secret with fine-grained service permissions in the 'API Management' section of the 'Profile' tab. These credentials must be provided in the /profile/api/v1/auth/token route in order to acquire a JWT to make further requests with. This JWT is valid for one week; the credentials do not expire but may be deleted.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fivewestapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PairBaseClient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairBaseClient{}

// PairBaseClient struct for PairBaseClient
type PairBaseClient struct {
	BaseCurrency string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
}

type _PairBaseClient PairBaseClient

// NewPairBaseClient instantiates a new PairBaseClient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairBaseClient(baseCurrency string, quoteCurrency string) *PairBaseClient {
	this := PairBaseClient{}
	this.BaseCurrency = baseCurrency
	this.QuoteCurrency = quoteCurrency
	return &this
}

// NewPairBaseClientWithDefaults instantiates a new PairBaseClient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairBaseClientWithDefaults() *PairBaseClient {
	this := PairBaseClient{}
	return &this
}

// GetBaseCurrency returns the BaseCurrency field value
func (o *PairBaseClient) GetBaseCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseCurrency
}

// GetBaseCurrencyOk returns a tuple with the BaseCurrency field value
// and a boolean to check if the value has been set.
func (o *PairBaseClient) GetBaseCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseCurrency, true
}

// SetBaseCurrency sets field value
func (o *PairBaseClient) SetBaseCurrency(v string) {
	o.BaseCurrency = v
}

// GetQuoteCurrency returns the QuoteCurrency field value
func (o *PairBaseClient) GetQuoteCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteCurrency
}

// GetQuoteCurrencyOk returns a tuple with the QuoteCurrency field value
// and a boolean to check if the value has been set.
func (o *PairBaseClient) GetQuoteCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteCurrency, true
}

// SetQuoteCurrency sets field value
func (o *PairBaseClient) SetQuoteCurrency(v string) {
	o.QuoteCurrency = v
}

func (o PairBaseClient) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairBaseClient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["base_currency"] = o.BaseCurrency
	toSerialize["quote_currency"] = o.QuoteCurrency
	return toSerialize, nil
}

func (o *PairBaseClient) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base_currency",
		"quote_currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPairBaseClient := _PairBaseClient{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPairBaseClient)

	if err != nil {
		return err
	}

	*o = PairBaseClient(varPairBaseClient)

	return err
}

type NullablePairBaseClient struct {
	value *PairBaseClient
	isSet bool
}

func (v NullablePairBaseClient) Get() *PairBaseClient {
	return v.value
}

func (v *NullablePairBaseClient) Set(val *PairBaseClient) {
	v.value = val
	v.isSet = true
}

func (v NullablePairBaseClient) IsSet() bool {
	return v.isSet
}

func (v *NullablePairBaseClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairBaseClient(val *PairBaseClient) *NullablePairBaseClient {
	return &NullablePairBaseClient{value: val, isSet: true}
}

func (v NullablePairBaseClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairBaseClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


